//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavtechAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Product_ApiEntities : DbContext
    {
        public Product_ApiEntities()
            : base("name=Product_ApiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Delivery_Slots> Delivery_Slots { get; set; }
        public virtual DbSet<Item_table> Item_table { get; set; }
        public virtual DbSet<Order_details> Order_details { get; set; }
        public virtual DbSet<Product_details> Product_details { get; set; }
    }
}
