//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavtechAPI.Models
{
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public int Id { get; set; }
        public Nullable<int> Cart_Value { get; set; }
        public string Customer_Id { get; set; }
        public string Delivery_Slot { get; set; }
        public string Delivery_Date { get; set; }
        public Nullable<System.DateTime> Order_Time { get; set; }
    }
}
