//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavtechAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_details
    {
        public int Id { get; set; }
        public string ProductId { get; set; }
        public string Brand { get; set; }
        public string Product { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
